Bittrex ws
EmergentCybernetics/ExchangeSharp pull request #1
Opened 2021-07-06 06:42 UTC by adrianbegi

Implemented bittrex websocket
https://bittrex.github.io/api/v3#definition-SocketResponse

Updated from v1 implementation to v3 implementation
https://bittrex.github.io/guides/v3/upgrade

Implemented OnGetPositionWebSocket although Bittrex only returns orders not positions.

2021-07-08 02:43 UTC, EmergentCybernetics requested changes
@adrianbegi First pass here looks good. The order/position updates are working for me now. We do need to get `OnGetDeltaOrderBookWebSocketAsync()` added next. It only needs to support the public WebSocket. Please take a look at that when you can.

Thanks!

2021-07-08 02:43 UTC, EmergentCybernetics commented on src/ExchangeSharp/API/Exchanges/Bittrex/ExchangeBittrexAPI_WebSocket.cs
> +				"trade_BTC-USD",
@adrianbegi What's the reason for `trade_BTC-USD` here? I'm not following what this channel is used for.

2021-07-08 02:43 UTC, EmergentCybernetics commented on src/ExchangeSharp/API/Exchanges/Bittrex/ExchangeBittrexAPI_WebSocket.cs
> -		protected override async Task<IWebSocket> OnGetDeltaOrderBookWebSocketAsync
@adrianbegi We'll need you to implement the `OnGetDeltaOrderBookWebSocketAsync()` function for Bittrex v3 WS next.

2021-07-08 02:43 UTC, EmergentCybernetics commented on src/ExchangeSharp/Utility/SignalrManager.cs
>      public class SignalrManager
@adrianbegi It looks like you ended up not using `SignalrManager`. Let's go ahead and remove the file as it's no longer needed.

2021-07-08 02:46 UTC, adrianbegi commented on src/ExchangeSharp/API/Exchanges/Bittrex/ExchangeBittrexAPI_WebSocket.cs
> +				"trade_BTC-USD",
Sorry I just added that for testing to make sure I can subscrive to trades, will remove

2021-07-13 15:16 UTC, EmergentCybernetics approved these changes

2021-07-13 15:24 UTC, EmergentCybernetics commented
Closing. Merged via https://github.com/EmergentCybernetics/ExchangeSharp/pull/2

2021-07-13 15:24 UTC, closed without merging